### ISSUE TITLE
Resolution not preserved after game restart

### ISSUE THREAD

**Issue by tanieltari** [CookiePLMonster/SilentPatchScarface#10]
Hi!
First of all thanks for publishing this patch.
Ive found an issue that after game restart the resolution is set back to default. 
settings.ini file is created and contains correct info
Also are you planning to release more optimizations for this game, because it still has low framerate at some places.
Thanks!

**Comment by tanieltari** [comment]
![image](https://user-images.githubusercontent.com/14837490/82357759-38b7a300-9a0e-11ea-8d1c-d7cb183e167c.png)
![image](https://user-images.githubusercontent.com/14837490/82357834-55ec7180-9a0e-11ea-85d6-4077095a8124.png)

**Comment by CookiePLMonster** [comment]
From what I know, it's a SP bug when using an older game version. I strongly recommend updating the game to 1.00.2 - not only it comes with legitimate improvements, but SilentPatch has also been tested best on this version.

**Comment by CookiePLMonster** [comment]
I assume patching the game to 1.00.2 has helped.
