### ISSUE TITLE
CPU Affinity

### ISSUE THREAD

**Issue by Streitpferd** [CookiePLMonster/SilentPatchScarface#11]
Just wanted to inform you and maybe help others! With Patch 1.002 installed and your SilentPatch the Game starts with all Cores checked in the Task Manager. This caused a bug for me, where i was not able to Load my Profile because it simply showed no Text. The Window was there, but i could only press ESC to start a new Game. When i start a new Game, minimize it immediately after the start, and select only 1 Core in the Task Manager, it shows the Text for loading my Profile. This does not happen with Version 1.0 and your Patch because with this Version only 1 Core is already checked. I maybe know why this happens, this could be caused by AMD's Ryzen CPU Count which is different from other CPU's. Also another issue i have is that the Sun Flickers inside and outside of the World which does not happen when i use the Wine Glider Solution.
![Bug1](https://user-images.githubusercontent.com/66419477/83751884-e3af9a00-a667-11ea-9654-348df28f6a3f.jpg)
![Bug2](https://user-images.githubusercontent.com/66419477/83751888-e611f400-a667-11ea-9645-54ac7ee99560.jpg)
![SunBug](https://user-images.githubusercontent.com/66419477/83751894-e7dbb780-a667-11ea-826c-95cccdb64917.jpg)

**Comment by CookiePLMonster** [comment]
Dang, that's annoying. Looks like letting the game run loose on all cores was a mistake after all - for the next release, I will definitely have to make this an INI option.

The reason it works "fine" for you on 1.00 is because that fix is likely glitched on that release, and just doesn't apply.

**Comment by Ekooo08** [comment]
> Dang, that's annoying. Looks like letting the game run loose on all cores was a mistake after all - for the next release, I will definitely have to make this an INI option.
> 
> The reason it works "fine" for you on 1.00 is because that fix is likely glitched on that release, and just doesn't apply.

Hello any updates for the Version 1.002? I also have the same problem. Thanks

**Comment by Aamember12403** [comment]
Is there anything that has been done to resolve this yet? A way to select how many cores?

**Comment by CookiePLMonster** [comment]
There is a linked PR pending that introduces an INI option to toggle this on/off, but before I merge it I want to try one more thing as seen in the widescreen fix for NFS UG2:
https://github.com/ThirteenAG/WidescreenFixesPack/pull/1045

I suspect this trick may help keep the performance benefit of setting affinity freely without having the game fall apart, but I need to find some time to investigate it.

**Comment by Aamember12403** [comment]
Thank you. I did manage to get it to load saves by using task manager and setting affinity to just one core. It does look like after you do the initial load you can save and load after switching it back to all cores. However you have to switch it back to get it to load again upon restarting the game. 

Sent from the all new AOL app for Android 
 
  On Wed, Feb 9, 2022 at 4:29 AM, ***@***.***> wrote:   


There is a linked PR pending that introduces an INI option to toggle this on/off, but before I merge it I want to try one more thing as seen in the widescreen fix for NFS UG2:
ThirteenAG/WidescreenFixesPack#1045

I suspect this trick may help keep the performance benefit of setting affinity freely without having the game fall apart, but I need to find some time to investigate it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CookiePLMonster** [comment]
> Thank you. I did manage to get it to load saves by using task manager and setting affinity to just one core. It does look like after you do the initial load you can save and load after switching it back to all cores. However you have to switch it back to get it to load again upon restarting the game.

I tried that locally and I can't reproduce the issue on two PCs in total - but that's the nature of threading issues, and it's still very believeable. I should be able to try out that idea from NFS UG2 very soon and I will provide a test build in the PR, so it could be verified before it goes into a released product.
