### ISSUE TITLE
No performance improvements when using Ryzen Cpu

### ISSUE THREAD

**Issue by Bun01294** [CookiePLMonster/SilentPatchScarface#12]
I'm not getting any performance improvements when using a ryzen cpu, i rarely hit 60fps and getting massive frame drops that you described in your blog. The .asi plugin does activate the multicore use for the game but i cant see any gains.

**Comment by Bun01294** [comment]
![Scarface_2020_10_20_01_30_37_435](https://user-images.githubusercontent.com/73011351/96561101-fbcd3200-1273-11eb-9ef2-aa8dee088d03.jpg)

**Comment by Bun01294** [comment]
I like to point out again that all cores are checked/used in task manager, but for some odd reasons only cpu12 is used.

**Comment by CookiePLMonster** [comment]
It might be that the game can't account for as many CPU cores. I should have pointed it out in the patch notes, but the fact it's now running on all cores does not **guarantee** performance improvements.

**Comment by Bun01294** [comment]
Oh, case closed then
