### ISSUE TITLE
Game doesn't save

### ISSUE THREAD

**Issue by 1232323123xasdasd123** [CookiePLMonster/SilentPatchScarface#2]
After using the Silent Patch my game doesn't allow me to save, the prompt appears in the game just like it originally did, but when relauching the game my profile is gone, as well as my saves.

The silent patch also doesn't seem to create the settings.ini, I'm not sure if both of these problems are related.

**Comment by CookiePLMonster** [comment]
I'm pretty sure this has nothing to do with SilentPatch specifically. The game saves to its own game directory, and so if you installed it to any protected directory (such as Program Files), you might encounter issues like this.

**Comment by 1232323123xasdasd123** [comment]
Managed to fix it pal, I deleted the configuration files located in the registry, more specifically the entire VUGAMES folder, then I reinstalled the game, and it loaded my save right up.

**Comment by CookiePLMonster** [comment]
Hm, registry should be unused now, but there is currently an issue with registry's removal in 1.0. We'll see how it works after I hotfix it I guess!
