### ISSUE TITLE
Scarface Fusion Fix doesn't work

### ISSUE THREAD

**Issue by hxazgalor** [CookiePLMonster/SilentPatchScarface#28]
I applied the Silent Patch for Scarface and the game ran fine, but when I unpack the Fusion Fix zip folder's contents to the game's directory, the game refuses to launch. I get this error when I try to launch the game.

![kYAa2LwjiX](https://github.com/CookiePLMonster/SilentPatchScarface/assets/12862476/a63078b6-3382-4b98-b6e4-aa7605d593d8)

Any advice would be appreciated.

**Comment by hxazgalor** [comment]
UPDATE: Removing the d3d9.dll and d3d9.ini files seem to have resolved the issue, but I don't understand why this is the case. Would appreciate clarification, if possible.

**Comment by CookiePLMonster** [comment]
I don't know what Fusion Fix is doing that an issue like this happens, especially since SP alone works fine. Your initial issue was posted in the correct place, as Fusion Fix is ThirteenAG's, not mine.

**Comment by CookiePLMonster** [comment]
I'll close this for now, feel free to reopen if further info shows that it's indeed something with SP. That is unlikely though, worst case it may be to something like my ASI loader not being up to date.

FWIW error C000007B is a "bad image" error, maybe the download just got corrupted?

**Comment by hxazgalor** [comment]
Which download, the game itself or the fix? I didn't get any errors downloading the fix from both Nexus Mods and GitHub; otherwise, the zip probably wouldn't work. If it's the game, I would think it'd be giving me more problems than it is now, as it's running fine.

**Comment by CookiePLMonster** [comment]
> Which download, the game itself or the fix?

Whatever came with `d3d9.dll`, so most likely Fusion Fix. You are likely right about the zip file being corrupted otherwise, but it's still worth a try.

**Comment by hxazgalor** [comment]
I just got a reply from ThirteenAG, who provided a direct DL link to the d3d9 files. Applying that also caused the same error.
