### ISSUE TITLE
Support for EU release?

### ISSUE THREAD

**Issue by wolfinston85** [CookiePLMonster/SilentPatchScarface#4]
Hello, I recently installed Silent Patch in the us version of the game and it played perfectly fine, however, my eu retail copy seems to ignore silent patch altogether, given that it crashes when I try to change my resolution to anything higher than the default, and the game also seems to still run in one core instead of using all of my cpu's available cores.

I have both the us, as well as the eu version of the game, english isn't my first language, so I would prefer to play the eu version of the game that has support for my language.

I was wondering if there was a plan for a future update that could offer support for more versions?

I have both tried the 1.0 version of the game, and the 1.00.2 version of the game without too much success.

Thanks in advance.

**Comment by CookiePLMonster** [comment]
Hey,

it's totally possible sadly, especially if this executable has DRM. I might need that EXE for reference.

**Comment by wolfinston85** [comment]
[Scarface.zip](https://github.com/CookiePLMonster/SilentPatchScarface/files/4412676/Scarface.zip)


Sorry for the late reply, I have attached the .exe that I'm using, it's supposed to be patched to the 1.00.2 version, hope it helps.

**Comment by wolfinston85** [comment]
Okay after 5 months, and a little luck I've managed to fix the problem.

Buckle up, because it's quite a long read...

Turns out the reason as to why it was crashing, was because of the configuration files conflicting with the silent patch configuration files.

So what I did in order to fix this was to delete all of my Scarface configuration files before installing the SilentPatch, I had to make sure to delete both the 32bit, and 64 bit registry keys given that the game creates both of these depending on wether you launch it with administration permissions or not, the registry keys are.

64 bit: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\VUGAMES\Scarface\

and

32 bit: HKEY_CURRENT_USER\Software\Classes\VirtualStore\MACHINE\SOFTWARE\Wow6432Node

You need to make sure to have DELETED both of these keys in order to launch the game using SilentPatch.

Now, the problem with the resolution changed happenned only in one of my pc's, I don't know why but whenever I would change the resolution in game, after the first cutscene, the game basically would show a black screen and then it wouldn't allow me to get back into it, I believe this has to do with the way new Windows 10 updates are handling windowed fullscreen, and exclusive fullscreen.

Either way, the way I managed to resolve this issue, was by selecting my resolution, waiting for the black screen to appear, then click enter on my keyboard as to confirm the resolution option.

Despite not being able to see the game, I would hear a sound confirming the resolution change, then I would alt-f4 out of the game, restart it, and the game respected my resolution change.

I'm not sure if you can do the same by simply starting the game with SilentPatch after deleting the aforementioned configuration files within the regedit, and then changing directly the resolution using the settings.ini file that SilentPatch creates within the game directory, but it's worth a shot.

Other than that, thank you for this patch, you made an old man really, really happy.
