### ISSUE TITLE
Folders structure

### ISSUE THREAD

**Issue by Sagatt** [CookiePLMonster/SilentPatchScarface#5]
Could it be possible to change where the .exe reads the game files? 
Instead of the .exe reading the .rpf files just make a .bat that unpacks the files and puts them into different folders.

Cement.rpf --> Cement Folder
Sound1.rpf --> Cement Folder
Sound2.rpf --> Cement Folder
__
Movies --> Movies Folder

The game is already capable of running if you just unpack the rpf files on the game folder, but then the folder becomes a mess, very un-organized, so if it ain't much to ask could that be addressed in a next update? Make it optional.

**Comment by CookiePLMonster** [comment]
How is this in the scope of SilentPatch, which is supposed to be more or less strictly about fixing issues?

**Comment by Sagatt** [comment]
I don't know, i just thought it would be a cool thing to add, since you're a modder and this could help future modding, i'm not sure how hard implementing that would be nor if you'd be interested, but i thought i could make this suggestion
