### ISSUE TITLE
Bug on mission 3

### ISSUE THREAD

**Issue by Sagatt** [CookiePLMonster/SilentPatchScarface#7]
The game keeps crashing at various points during mission 3 where you go into gomez's suite in the hotel and shoot up the place.
It crashes either after throwing the guy off the building in the cutscene or entering the elevator to the garage.

**Comment by CookiePLMonster** [comment]
That sounds pretty worrying. Does the same happen if game is locked to one CPU again? You could do it via Task Manager (after launching the game) via "Set Affinity" option.

Alternately it could be some edge case for the vertex buffer pool but that I'll need to test and verify myself.

**Comment by Sagatt** [comment]
The bug does not occur without the silentpatch, after the mission has been passed i've simply used your fix back again and had no more issues, also i've had people say they had crashes on the mission 3 but after some tries the game progressed normally with silentpatch installed.

**Comment by CookiePLMonster** [comment]
I see - hence I said, it would be good to nail it down to a specific fix, and you can do it by modifying the process CPU affinity from Task Manager.

I guess I'l take a look at it during the weekend, if it crashes every time it shouldn't be hard to reproduce.

**Comment by MixMax0995** [comment]
Hi there! I got the same problem as mentioned by Sagatt.
After patching the game to the official patch version 1.00.2 (preferably US) the game stopped crashing at this point. I guess that this was the fix as I didn't lock the game on one CPU core.

**Comment by CookiePLMonster** [comment]
Well then. If it's still happening after I release Build 2, let's reopen.
